BreakingNewsWeb/Models/Article.cs
using Microsoft.EntityFrameworkCore;

namespace BreakingNewsWeb.Models;

[Index("Id")]
public partial class Article
{
    public int Id { get; set; }

    public string? Source { get; set; }

    public string? Author { get; set; }

    public string? Title { get; set; }

    public string? Description { get; set; }

    public string? Url { get; set; }

    public string? UrlToImage { get; set; }

    public DateTime? PublishedAt { get; set; }

    public string? Content { get; set; }
}

BreakingNewsWeb/Components/SourceFilterViewComponent.cs
using DBConnection.Models.Contexts;
using Microsoft.AspNetCore.Mvc;

namespace BreakingNewsWeb.Components
{
    public class SourceFilterViewComponent:ViewComponent
    {
        private readonly NewsContext newsDb;
        public SourceFilterViewComponent(NewsContext newsContext)
        {
            // получаем контекст newsDB
            newsDb = newsContext;
        }
        public IViewComponentResult Invoke()
        {
            var data = newsDb.articles
                .Select(x => x.Source)
                .Distinct()
                .OrderBy(x => x);
            return View(data);
        }
    }
}

BreakingNewsWeb/Controllers/HomeController.cs
using BreakingNewsWeb.Models;
using BreakingNewsWeb.Models.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using DBConnection.Models.Contexts;
using DBConnection.Models.Classes;

namespace BreakingNewsWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly NewsContext newsDb;

        public HomeController(NewsContext newsContext)
        {
            // получаем контекст newsDB
            newsDb = newsContext;
        }

        public async Task<IActionResult> Index()
        {
            // количество выводимых статей на Index
            int articlesQuantity = 20;

            // Выбираем N последних статей из базы для Index, для вывода последних добавленных
            var reverseArticlesList = await newsDb.articles.OrderByDescending(a => a.Id).Take(articlesQuantity).ToListAsync();

            // передаём список статей в предствление
            return View(reverseArticlesList);
        }

        public async Task<IActionResult> Articles(string? source, int page = 1)
        {
            // обозначаем количество статей на странице
            int articlesOnPage = 7;

            // создаём список статей с информацией о странице
            var data = new ArticlesListViewModel
            {

                Articles = await newsDb.articles
                            .Where(p => source == null || p.Source == source)
                            .OrderByDescending(x => x.Id)
                            .Skip((page - 1) * articlesOnPage)
                            .Take(articlesOnPage)
                            .ToListAsync(),
                PagingInfo = new PagingInfo
                            {
                                CurrentPage = page,
                                ItemsPerPage = articlesOnPage,
                                TotalItems = source == null ? newsDb.articles.Count() : newsDb.articles.Where(a => a.Source == source).Count()
                            },
                CurrentSource = source
            };
            return View(data);
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

BreakingNewsWeb/Views/Home/About.cshtml
@using BreakingNewsWeb.Models;

@{
    ViewData["Title"] = "Privacy Policy";
}

BreakingNewsWeb/Views/Home/Articles.cshtml
@using BreakingNewsWeb.Controllers;
@using BreakingNewsWeb.Models;

@model ArticlesListViewModel;

@{
    ViewBag.PageInfo = "Articles collection:";
}

<div> 
    <vc:source-filter/>
</div>

<div page-model="@Model.PagingInfo" page-action="Articles"
        page-classes-enabled="true"
        page-class="btn" page-class-normal="btn-outline-secondary"
        page-class-disabled="disabled"
        page-class-selected="btn-secondary" 
        page-url-category="@Model?.CurrentSource!"
        class="btn-group dropdown-menu-left mb-4" >
</div>

@foreach (var article in Model?.Articles!)
{
    <div class="articles">
        <img class="articles__img" src="@article.UrlToImage"/>
        <div class="articles__text">
            <div class="articles__title">@article.Title</div>
            <div class="articles__content">@article.Content</div>
            <div class="text-muted mt-2">@article.Source - @article.PublishedAt</div>
            <a class="articles__more btn btn-light mt-2 col-1 btn-sm" href="@article.Url">More</a>
        </div>
    </div>
}

<div page-model="@Model.PagingInfo" page-action="Articles"
        page-classes-enabled="true"
        page-class="btn" page-class-normal="btn-outline-secondary"
        page-class-disabled="disabled"
        page-class-selected="btn-secondary"
        page-url-category="@Model?.CurrentSource!"
        class="btn-group dropdown-menu-left mb-4" >
</div>

BreakingNewsWeb/Views/Home/Index.cshtml
@using BreakingNewsWeb.Controllers;
@using BreakingNewsWeb.Models;
@using DBConnection.Models.Classes;

@model IEnumerable<Article>;

@{
    int count = 0;

    // quantityArticlesOnPage задаёт количество выводимых статей на страницу Index
    int quantityArticlesOnPage = 20;

    var mainArticle = Model.First();

    ViewBag.PageInfo = $"Last news on {DateTime.Now.ToShortDateString()}";
}
<div class="main">
    <div class="mainArticle">
        <img class="main-img img-thumbnail" src="@mainArticle.UrlToImage"/>
        <div class="title">@mainArticle.Title</div>
        <div class="content">@mainArticle.Content</div>
        <div class="text-muted mt-2">@mainArticle.Source - @mainArticle.PublishedAt</div>
        <a class="more btn btn-light mt-2 col-2" href="@mainArticle.Url">More</a>
    </div>

    @foreach (var article in Model)
    {
        if (count < quantityArticlesOnPage)
        {
            <div class="article class-@count">
                <img class="img img-thumbnail" src="@article.UrlToImage"/>
                <div class="title">@article.Title</div>
                <div class="content">@article.Content</div>
                <div class="text-muted mt-2">@article.Source - @article.PublishedAt</div>
                <a class="more btn btn-light mt-1 col-3" href="@article.Url">More</a>
            </div>
            count++;
        }
        else break;
    }
</div>